# constants.py

ADMIN = "ADMIN"
MANAGER = "MANAGER"
EMPLOYEE = "EMPLOYEE"

ROLES = [ADMIN, MANAGER, EMPLOYEE]
ERROR_UNAUTHORIZED = "Unauthorized"
ERROR_FORBIDDEN = "Forbidden"
ERROR_NOT_FOUND = "Not found"
